In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [3]:
url='https://raw.githubusercontent.com/saikishore2121/machine-learning-online-2018/master/Datasets/Mushrooms/mushrooms.csv'
df=pd.read_csv(url,error_bad_lines=False)

In [4]:
df.head()

type cap_shape cap_surface cap_color bruises odor gill_attachment  \
0    p         x           s         n       t    p               f   
1    e         x           s         y       t    a               f   
2    e         b           s         w       t    l               f   
3    p         x           y         w       t    p               f   
4    e         x           s         g       f    n               f   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring_number ring_type spore_print_color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [5]:
le=preprocessing.LabelEncoder()

In [6]:
ds=df.apply(le.fit_transform)

In [7]:
print(type(ds))

<class 'pandas.core.frame.DataFrame'>


In [8]:
ds=ds.values

In [9]:
print(type(ds))

<class 'numpy.ndarray'>


In [10]:
print(ds[:5,:])

[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [11]:
ds_y=ds[:,0]
ds_x=ds[:,1:]

In [12]:
X_train,X_test,Y_train,Y_test=train_test_split(ds_x,ds_y,test_size=0.2)

In [17]:
print(X_train.shape,Y_train.shape)

(6499, 22) (6499,)


In [16]:
def prior_prob(Y_train,label):
    a=(Y_train==label)
    a=np.sum(a)
    return (a)/(float)(Y_train.shape[0])

In [23]:
def conditional_prob(X_train,Y_train,feature_col,feature_val,label):
    m=X_train.shape[0]
    count=0
    for i in range (m):
        if(X_train[i][feature_col]==feature_val and Y_train[i]==label):
            count+=1
    denominator=np.sum(Y_train==label)
    return (count)/(float)(denominator)

In [34]:
def predict(X_train,Y_train,xtest):
    classes=np.unique(Y_train)
    n_features=X_train.shape[1]
    post_probs=[]
    for label in classes:
        likelihood=1.0
        for j in range(n_features):
            cond_prob=conditional_prob(X_train,Y_train,j,xtest[j],label)
            likelihood*=cond_prob
        prior=prior_prob(Y_train,label)
        post_probs.append(prior*likelihood)
    
    post_probs=np.array(post_probs)
    max_arg=np.argmax(post_probs)
    return classes[max_arg]

In [36]:
pred=predict(X_train,Y_train,X_test[2])
print(pred)

0


In [ ]:
def score(X_train,Y_train,X_test,Y_test):
    m=X_test.shape[0]
    pred=[]
    for i in range(m):
        pred.append(predict(X_train,Y_train,X_test[i]))
    pred=np.array(pred)
    pred_score=np.sum(pred==Y_test)/Y_test.shape[0]
    return pred_score

In [ ]:
accuracy=score(X_train,Y_train,X_test,Y_test)
print(accuracy)